---
title: "Run Statistics Report"
output: html_document
editor_options: 
  chunk_output_type: console
params:
  log_dir: "~/../../Volumes/RBL_NCI-1/Wolin/Sam/testb/log/20211117_1418/"
---

```{r include=FALSE}
library("rjson")
library(ggplot2)
library(ggpubr)
```

<!-- # Set params, output   -->
```{r echo=F, message=FALSE, warning=FALSE, eval=T, include=F,results=F,}
#set log dir
log_dir=params$log_dir

#read in stats file
stats_file <- fromJSON(file = paste0(log_dir,"snakemake.stats"))

#global func
`%notin%` <- Negate(`%in%`)
```

```{r include=FALSE}
#Process Rules
rule_list = names(stats_file$rules)

rules_df = data.frame()
for (i in 1:length(rule_list)){
  rules_df[nrow(rules_df)+1,"rule_name"] = rule_list[i]
  rules_df[nrow(rules_df),"mean"] = stats_file$rules[rule_list[i]][[1]][[1]]
  rules_df[nrow(rules_df),"min"] = stats_file$rules[rule_list[i]][[1]][[2]]
  rules_df[nrow(rules_df),"max"] = stats_file$rules[rule_list[i]][[1]][[3]]
}

```

```{r include=FALSE}
#process files
files_complete = names(stats_file$files)
files_df = data.frame()

#alignment
subset_value = "02_alignment"
files_subset = files_complete[grep(subset_value,files_complete)]

for (i in 1:length(files_subset)){
  files_df[nrow(files_df)+1,"rule_name"] = "alignment" 
  files_df[nrow(files_df),"file_name"] = strsplit(files_subset[1],"/")[[1]][length(strsplit(files_subset[1],"/")[[1]])]
  files_df[nrow(files_df),"duration"] = stats_file$files[files_subset[i]][[1]][[3]]
  files_df[nrow(files_df),"cores"] = stats_file$files[files_subset[i]][[1]][[5]][[1]]
  files_df[nrow(files_df),"nodes"] = stats_file$files[files_subset[i]][[1]][[5]][[2]]
}

#annotations
subset_value = "annotation_final_report.html"
files_subset = files_complete[grep(subset_value,files_complete)]

for (i in 1:length(files_subset)){
  files_df[nrow(files_df)+1,"rule_name"] = "annotation" 
  files_df[nrow(files_df),"file_name"] = strsplit(files_subset[1],"/")[[1]][length(strsplit(files_subset[1],"/")[[1]])]
  files_df[nrow(files_df),"duration"] = stats_file$files[files_subset[i]][[1]][[3]]
  files_df[nrow(files_df),"cores"] = stats_file$files[files_subset[i]][[1]][[5]][[1]]
  files_df[nrow(files_df),"nodes"] = stats_file$files[files_subset[i]][[1]][[5]][[2]]
}

#cleanup
subset_value = "03_genomic"
files_subset = files_complete[grep(subset_value,files_complete)]

for (i in 1:length(files_subset)){
  files_df[nrow(files_df)+1,"rule_name"] = "cleanup" 
  files_df[nrow(files_df),"file_name"] = strsplit(files_subset[1],"/")[[1]][length(strsplit(files_subset[1],"/")[[1]])]
  files_df[nrow(files_df),"duration"] = stats_file$files[files_subset[i]][[1]][[3]]
  files_df[nrow(files_df),"cores"] = stats_file$files[files_subset[i]][[1]][[5]][[1]]
  files_df[nrow(files_df),"nodes"] = stats_file$files[files_subset[i]][[1]][[5]][[2]]
}

#create bams
subset_value = "05_unique|05_mm|02_merged"
files_subset = files_complete[grep(subset_value,files_complete)]

for (i in 1:length(files_subset)){
  files_df[nrow(files_df)+1,"rule_name"] = "create_bams" 
  files_df[nrow(files_df),"file_name"] = strsplit(files_subset[i],"/")[[1]][length(strsplit(files_subset[i],"/")[[1]])]
  files_df[nrow(files_df),"duration"] = stats_file$files[files_subset[i]][[1]][[3]]
  files_df[nrow(files_df),"cores"] = stats_file$files[files_subset[i]][[1]][[5]][[1]]
  files_df[nrow(files_df),"nodes"] = stats_file$files[files_subset[i]][[1]][[5]][[2]]
}

#dedup
subset_value = "03_dedup"
files_subset = files_complete[grep(subset_value,files_complete)]

for (i in 1:length(files_subset)){
  files_df[nrow(files_df)+1,"rule_name"] = "dedup" 
  files_df[nrow(files_df),"file_name"] = strsplit(files_subset[i],"/")[[1]][length(strsplit(files_subset[i],"/")[[1]])]
  files_df[nrow(files_df),"duration"] = stats_file$files[files_subset[i]][[1]][[3]]
  files_df[nrow(files_df),"cores"] = stats_file$files[files_subset[i]][[1]][[5]][[1]]
  files_df[nrow(files_df),"nodes"] = stats_file$files[files_subset[i]][[1]][[5]][[2]]
}

#peaks
subset_value = "03_peaks"
files_subset = files_complete[grep(subset_value,files_complete)]

for (i in 1:length(files_subset)){
  files_df[nrow(files_df)+1,"rule_name"] = "peaks" 
  files_df[nrow(files_df),"file_name"] = strsplit(files_subset[i],"/")[[1]][length(strsplit(files_subset[i],"/")[[1]])]
  files_df[nrow(files_df),"duration"] = stats_file$files[files_subset[i]][[1]][[3]]
  files_df[nrow(files_df),"cores"] = stats_file$files[files_subset[i]][[1]][[5]][[1]]
  files_df[nrow(files_df),"nodes"] = stats_file$files[files_subset[i]][[1]][[5]][[2]]
}

#mapq recalc
subset_value = "_recalculated.bam"
files_subset = files_complete[grep(subset_value,files_complete)]

for (i in 1:length(files_subset)){
  files_df[nrow(files_df)+1,"rule_name"] = "mapq_recalc" 
  files_df[nrow(files_df),"file_name"] = strsplit(files_subset[i],"/")[[1]][length(strsplit(files_subset[i],"/")[[1]])]
  files_df[nrow(files_df),"duration"] = stats_file$files[files_subset[i]][[1]][[3]]
  files_df[nrow(files_df),"cores"] = stats_file$files[files_subset[i]][[1]][[5]][[1]]
  files_df[nrow(files_df),"nodes"] = stats_file$files[files_subset[i]][[1]][[5]][[2]]
}

#fix numeric
files_df$duration=as.numeric(files_df$duration)

#get sample and type
for (i in rownames(files_df)){
  files_df[i,"sampleid"] = strsplit(files_df[i,"file_name"],"[.]")[[1]][1]
  files_df[i,"type"] = strsplit(files_df[i,"file_name"],"[.]")[[1]][2]
}
files_df$sampleid = gsub("_all|_unique|_annotation_final_report","",files_df$sampleid)
files_df$type = gsub("dedup|mapq_recalculated|bed|SAF|html","",files_df$type)
```

The following provides boxplots for each rule, with min, mean, and maximum values provided. 
- Quicker rules (A,B) are shown first, followed by slower rules (C).

```{r echo=FALSE}
plotting_rules<-function(type_in){
    #short rules
    if(type_in=="slow"){
      #split plot into two
    p1 = subset(rules_df, rule_name %notin%
           c("qc_alignment", "mapq_recalc", "mapq_stats", "annotation_report"))[1:8,] %>%
      ggplot(aes(x = rule_name, ymin = min, lower=min, middle = mean, upper = max, ymax = max)) + 
      geom_boxplot(stat="identity") + 
      theme(axis.text.x = element_text(angle=90, hjust=1),
            axis.title.x = element_blank())
    
    p2 =  subset(rules_df, rule_name %notin%
           c("qc_alignment", "mapq_recalc", "mapq_stats", "annotation_report"))[9:16,] %>%
      ggplot(aes(x = rule_name, ymin = min, lower=min, middle = mean, upper = max, ymax = max)) + 
      geom_boxplot(stat="identity") + 
      theme(axis.text.x = element_text(angle=90, hjust=1),
            axis.title.x = element_blank())
    
    pf = ggarrange(p1, p2,
                labels = c("A", "B"),
                ncol = 1, nrow = 2)
    pf = annotate_figure(pf, top = text_grob("Rule Times (seconds)", 
                    face = "bold", size = 14))
    } else{
      #long rules
      p3 = subset(rules_df, rule_name %in%
           c("qc_alignment", "mapq_recalc", "mapq_stats", "annotation_report")) %>%
      ggplot(aes(x = rule_name, ymin = min, lower=min, middle = mean, upper = max, ymax = max)) + 
      geom_boxplot(stat="identity")+
      theme(axis.text.x = element_text(angle=90, hjust=1),
            axis.title.x = element_blank())
      
      pf = ggarrange(p3,
                labels = c("C"),
                ncol = 1, nrow = 1)
    }
  
  return(pf)
}

plotting_rules("slow")
plotting_rules("quick")
```

The following provides boxplots for each rule by sample, with total duration per rule provided. 
- Quicker rules (A) are shown first, followed by slower rules (B).

```{r echo=FALSE}
plotting_files<-function(){
  p1 = subset(files_df, rule_name %notin% c("annotation", "mapq_recalc")) %>%
    ggplot(aes(x=sampleid,y=duration, fill=type)) +
    geom_col(position = position_dodge()) + 
    facet_grid(~rule_name,scales="free") + 
    theme(axis.title.x = element_blank())
    
  p2 = subset(files_df, rule_name %in% c("annotation", "mapq_recalc")) %>%
    ggplot(aes(x=sampleid,y=duration, fill=sampleid)) +
    geom_col(position = position_dodge()) + 
    facet_grid(~rule_name,scales="free")
  
  pf = ggarrange(p1, p2,
                labels = c("A", "B"),
                ncol = 1, nrow = 2)
  pf = annotate_figure(pf, top = text_grob("Rule Times by samples (seconds)", 
                    face = "bold", size = 14))
  return(pf)
}

plotting_files()
```