# cluster configuration
__default__:
    gres: lscratch:256
    mem: 96g
    partition: norm
    time: 10-00:00:00
    threads: 32
    output: ${{SLURM_JOBID}}.%j.{rule}.{wildcards}.out
    error: ${{SLURM_JOBID}}.%j.{rule}.{wildcards}.err
    
mapq_recalc:
    mem: 1TB
    partition: largemem
    
qc_alignment:
    mem: 1TB
    partition: largemem

create_beds:
    mem: 1TB
    partition: largemem
    time: 2-00:00:00