# cluster configuration
__default__:
    gres: lscratch:96
    mem: 40g
    partition: norm
    time: 00-12:00:00
    threads: 32
    output: .%j.{wildcards}.out
    error: .%j.{wildcards}.err

novoalign:
    time: 10-00:00:00
    mem: 96g

mapq_recalc:
    mem: 1TB
    partition: largemem
    
qc_alignment:
    mem: 1TB
    partition: largemem

create_beds:
    mem: 1TB
    partition: largemem
    time: 2-00:00:00