# cluster configuration
__default__:
    gres: lscratch:256
    mem: 96g
    partition: norm
    time: 10-00:00:00
    threads: 32

novoalign:
    mem: 100g
    partition: norm
    time: 10-00:00:00
    threads: 32
    
mapq_recalc:
    mem: 1TB
    partition: largemem
    time: 10-00:00:00
    threads: 32
    
qc_alignment:
    mem: 1TB
    partition: largemem
    time: 10-00:00:00
    threads: 32