# cluster configuration
__default__:
    gres: lscratch:96
    mem: 40g
    partition: ccr,norm
    time: 00-08:00:00
    threads: 32
    output: .%j.{wildcards}.out
    error: .%j.{wildcards}.err

qc_barcode:
    threads: 4
    time: 00-04:00:00

demultiplex:
    threads: 16
    mem: 32g
    time: 04-00:00:00

remove_adaptors:
    threads: 16
    time: 01-00:00:00
    mem: 32g

qc_fastq_pre:
    threads: 4
    mem: 3g
    time: 00-03:00:00

qc_fastq_post:
    threads: 4
    mem: 3g
    time: 00-03:00:00

qc_screen_validator:
    mem: 32g
    time: 00-03:00:00

split_files:
    threads: 4
    mem: 3g
    time: 00-03:00:00

novoalign:
    mem: 50g
    threads: 32
    time: 10-00:00:00

cleanup_conversion:
    threads: 8
    gres: lscratch:256
    mem: 120g
    time: 01-00:00:00

merge_unmapped_splits:
    threads: 8
    time: 01-00:00:00
    mem: 120g

create_bam_mm_unique:
    threads: 8
    gres: lscratch:256
    mem: 120g
    time: 01-00:00:00

merge_splits_unique_mm:
    threads: 32
    mem: 200g
    time: 01-00:00:00

merge_mm_and_unique:
    threads: 8
    gres: lscratch:256
    mem: 120g
    time: 01-00:00:00

qc_alignment:
    threads: 4
    mem: 120g

qc_troubleshoot:
    threads: 4
    mem: 3g

dedup:
    threads: 8
    mem: 120g
    gres: lscratch:256
    time: 01-00:00:00

create_beds_safs:
    mem: 200g
    gres: lscratch:512
    threads: 8

bgzip_beds:
    mem: 100g
    threads: 4

project_annotations:
    threads: 2
    mem: 10g
    time: 00-01:00:00

peak_annotations:
    threads: 4
    gres: lscratch:128
    mem: 30g
    time: 01-00:00:00

annotation_report:
    threads: 4
    gres: lscratch:128
    mem: 30g
    time: 00-12:00:00

MANORM_beds:
    threads: 4
    mem: 30g

DIFFBIND_beds:
    threads: 4
    mem: 30g
    
MANORM_analysis:
    threads: 4
    mem: 30g
    time: 01-00:00:00

DIFFBIND_preprocess:
    threads: 4
    mem: 30g

DIFFBIND_analysis:
    threads: 4
    mem: 30g

MANORM_post_processing:
    threads: 2
    mem: 30g
    time: 00-01:00:00

DIFFBIND_report:
    threads: 4
    mem: 30g

MANORM_RMD:
    threads: 2
    mem: 30g
    time: 00-01:00:00

mapq_recalc:
    threads: 8
    mem: 200g
    gres: lscratch:512
    time: 00-12:00:00

mapq_stats:
    threads: 8
    mem: 120g

feature_counts:
    threads: 8
    mem: 120g
    
