# Global configuration file for the pipeline
samples: '/home/sevillas2/git/iCLIP/config/samples_one.tsv' #need to update this
sample_manifest: '/home/sevillas2/git/iCLIP/config/samples_one.tsv'
multiplex_manifest: '/home/sevillas2/git/iCLIP/config/multiplex_one.tsv'
fastq_dir: '/data/sevillas2/iCLIP/fastq'
out_dir: '/data/sevillas2/iCLIP/output'
source_dir: '/home/sevillas2/git/iCLIP/workflow/'
novoalign_index: '/data/sevillas2/iCLIP/index/mm10_gencode_prerRNA/mm10_gencode_prerRNA'
minimum_count: 2
