hg38:
  std: '/data/RBL_NCI/iCLIP/index/hg38.nix'
  spliceaware:
    50bp: '/data/RBL_NCI/iCLIP/index/hg38_splice50bp.nix'
    75bp: '/data/RBL_NCI/iCLIP/index/hg38_splice75bp.nix'
    150bp: 'tbd'
mm10:
  std: '/data/RBL_NCI/iCLIP/index/mm10.nix'
  spliceaware:
    50bp: '/data/RBL_NCI/iCLIP/index/mm10_splice50bp.nix'
    75bp: '/data/RBL_NCI/iCLIP/index/mm10_splice75bp.nix'
    150bp: 'tbd'
