hg38:
  stardir: '/data/CCBR_Pipeliner/iCLIP/index/active/2022_0505/hg38/index'
  stargtf: '/data/CCBR_Pipeliner/iCLIP/index/active/2022_0505/hg38/ref/gencode.vM32.annotation.gtf'
  gencodepath: '/data/CCBR_Pipeliner/iCLIP/ref/annotations/hg38/Gencode_V32/fromGencode/gencode.v32.annotation.gtf.txt'
  refseqpath: '/data/CCBR_Pipeliner/iCLIP/ref/annotations/hg38/NCBI_RefSeq/GCF_000001405.39_GRCh38.p13_genomic.gtf.txt'
  canonicalpath: '/data/CCBR_Pipeliner/iCLIP/ref/annotations/hg38/Gencode_V32/fromUCSC/KnownCanonical/KnownCanonical_GencodeM32_GRCh38.txt'
  intronpath: '/data/CCBR_Pipeliner/iCLIP/ref/annotations/hg38/Gencode_V32/fromUCSC/KnownGene/KnownGene_GencodeV32_GRCh38_introns.bed'
  rmskpath: '/data/CCBR_Pipeliner/iCLIP/ref/annotations/hg38/repeatmasker/rmsk_GRCh38.txt'
  aliaspath: '/data/CCBR_Pipeliner/iCLIP/ref/annotations/hg38/hg38.chromAlias.txt'
  additionalannopath: '/data/CCBR_Pipeliner/iCLIP/ref/annotations/hg38/additional_anno/'
mm10:
  stardir: '/data/CCBR_Pipeliner/iCLIP/index/active/2022_0505/mm10/index'
  stargtf: '/data/CCBR_Pipeliner/iCLIP/index/active/2022_0505/mm10/ref/gencode.vM23.annotation.gtf'
  gencodepath: '/data/CCBR_Pipeliner/iCLIP/ref/annotations/mm10/Gencode_VM23/fromGencode/gencode.vM23.annotation.gtf.txt'
  refseqpath: '/data/CCBR_Pipeliner/iCLIP/ref/annotations/mm10/NCBI_RefSeq/GCF_000001635.26_GRCm38.p6_genomic.gtf.txt'
  canonicalpath: '/data/CCBR_Pipeliner/iCLIP/ref/annotations/mm10/Gencode_VM23/fromUCSC/KnownCanonical/KnownCanonical_GencodeM23_GRCm38.txt'
  intronpath: '/data/CCBR_Pipeliner/iCLIP/ref/annotations/mm10/Gencode_VM23/fromUCSC/KnownGene/KnownGene_GRCm38_introns.bed'
  rmskpath: '/data/CCBR_Pipeliner/iCLIP/ref/annotations/mm10/repeatmasker/rmsk_GRCm38.txt'
  aliaspath: '/data/CCBR_Pipeliner/iCLIP/ref/annotations/mm10/mm10.chromAlias.txt'
  additionalannopath: '/data/CCBR_Pipeliner/iCLIP/ref/annotations/mm10/additional_anno/'