# Global configuration file for the pipeline
#path to source directory
source_dir: "/home/sevillas2/git/iCLIP"

#path to output directory
output_dir: "/scratch/sevillas2/sam_test_master"

#path to manifest files
sample_manifest: "/data/CCBR_Pipeliner/iCLIP/test/sample_hg38_one.tsv"
multiplex_manifest: "/data/CCBR_Pipeliner/iCLIP/test/multiplex_hg38_one.tsv"

#path to fastq files
fastq_dir: "/data/CCBR_Pipeliner/iCLIP/test/"

#user parameters
multiplex_flag: "Y" #flag that samples are multiplexed ["Y","N"]
mismatch_allowance: 2 #number of nt mismatches allowed in barcodes; options [1,2]
split_value: 1000000 #number of sequences in split files [min 3000, default 1000000]
novoalign_reference: "hg38" #options: mm10 hg38
splice_aware: 'y' #options: Y or N
splice_bp_length: 50 # options: if splice_aware = Y, 50 or 75
minimum_count: 3 #minimum number of matches to count as a true peak
nt_merge: 50 #minimum distance of nucleotides to merge peaks
peak_id: "all" #report peaks for unique peaks only or unique and fractional mm ["unique","all"]
DE_method: "manorm" #choose DE method ["manorm","none"]
splice_junction: "n" #include splice junctions in peak calls
include_rRNA: "Y" #include refseq rRNA's in annotations ["Y", "N"]
condense_exon: "Y"

#modules, container parameters
container_dir: "/data/CCBR_Pipeliner/iCLIP/container"
bedtools: "bedtools/2.29.2"
bowtie2: "bowtie/2-2.3.4"
fastq_screen: "fastq_screen/0.14.0"
fastqc: "fastqc/0.11.9"
java: "java/12.0.1"
multiqc: "multiqc/1.9"
novocraft: "novocraft/4.03.01"
perl: "perl/5.24.3"
python: "python/3.7"
Qt: "Qt/5.13.2"
singularity: "singularity"
samtools: "samtools/1.11"
umitools: "umitools/1.1.1"
subread: "subread/2.0.1"
R: "R/4.0"