# Global configuration file for the pipeline
#path to snakemake file
source_dir: "/home/sevillas2/git/iCLIP/"

#path to output directory
output_dir: "/data/sevillas2/iCLIP/hg38_full/"

#path to manifest files
sample_manifest: "/data/RBL_NCI/iCLIP/test/sample_hg38_full.tsv"
multiplex_manifest: "/data/RBL_NCI/iCLIP/test/multiplex_hg38_full.tsv"

#path to fastq files
fastq_dir: "/data/RBL_NCI/iCLIP/test"

#path to containers
container_dir: "/data/RBL_NCI/iCLIP/container"

#user parameters
split_value: 2000000 #number of sequences in split files [min 3000, default 1000000]
novoalign_reference: "hg38" #options: mm10 hg38
splice_aware: 'y' #options: Y or N
splice_bp_length: 75 # options: if splice_aware = Y, 50,75,150
minimum_count: 2 #minimum number of matches to count as a true peak
