# Global configuration file for the pipeline
#path to snakemake file
source_dir: "/home/sevillas2/git/iCLIP/"

#path to output directory
output_dir: "/data/sevillas2/iCLIP/mm10/"

#path to manifest files
sample_manifest: "/data/RBL_NCI/iCLIP/test/sample_mm10_one.tsv"
multiplex_manifest: "/data/RBL_NCI/iCLIP/test/multiplex_mm10_one.tsv"

#path to fastq files
fastq_dir: "/data/RBL_NCI/iCLIP/test/"

#user parameters
mismatch_allowance: 1 #number of nt mismatches allowed in barcodes; options [1,2]
split_value: 3000 #number of sequences in split files [min 3000, default 1000000]
novoalign_reference: "mm10" #species ["mm10","hg38"]
splice_aware: 'n' #whether to run spliceaware in pipeline ["Y","N"]
splice_bp_length: 75 # splice aware bp_length [50,75,150]
minimum_count: 3 #minimum number of matches to count as a true peak [1,2,3]
nt_merge: 50 #minimum distance of nucleotides to merge peaks [10,20,30,40,50,60]
peak_id: "all" #report peaks for unique peaks only or unique and fractional mm ["unique","all"]
DE_method: "manorm" #choose DE method ["manorm","none"]

#modules, container parameters
container_dir: "/data/RBL_NCI/iCLIP/container"
bedtools: "bedtools/2.29.2"
bowtie2: "bowtie/2-2.3.4"
fastq_screen: "fastq_screen/0.14.0"
fastqc: "fastqc/0.11.9"
java: "java/12.0.1"
multiqc: "multiqc/1.9"
novocraft: "novocraft/4.03.01"
perl: "perl/5.24.3"
python: "python/3.7"
Qt: "Qt/5.13.2"
singularity: "singularity/3.7.0"
samtools: "samtools/1.11"
umitools: "umitools/1.1.1"
subread: "subread/2.0.1"
R: "R/4.0"