# Global configuration file for the pipeline
#path to snakemake file
source_dir: "/home/sevillas2/git/iCLIP/"

#path to output directory
output_dir: "/data/sevillas2/iCLIP/marco/"

#path to manifest files
sample_manifest: "/data/RBL_NCI/Wolin/CLIP_Pipeline/iCLIP/fCLIP/sam_test/samples.tsv"
multiplex_manifest: "/data/RBL_NCI/Wolin/CLIP_Pipeline/iCLIP/fCLIP/sam_test/multiplex.tsv"

#path to fastq files
fastq_dir: "/data/RBL_NCI/Wolin/CLIP_Pipeline/iCLIP/fCLIP/sam_test/"

#user parameters
mismatch_allowance: 1 #number of nt mismatches allowed in barcodes; options [1,2]
split_value: 1000000 #number of sequences in split files [min 3000, default 1000000]
novoalign_reference: "hg38" #options: mm10 mm10
splice_aware: 'y' #options: Y or N
splice_bp_length: 75 # options: if splice_aware = Y, 50,75,150
minimum_count: 3 #minimum number of matches to count as a true peak

#modules, container parameters
container_dir: "/data/RBL_NCI/iCLIP/container"
bowtie2: "bowtie/2-2.3.4"
fastq_screen: "fastq_screen/0.14.0"
perl: "perl/5.24.3"