#########################################################################################
# Global configuration file for the pipeline
#########################################################################################

#########################################################################################
#Folders and Paths
#########################################################################################
#path to iCLIP directory
sourceDir: "PIPELINE_HOME"
#path to output directory
outputDir: "OUTPUT_DIR"
#path to fastq files
fastqDir: "/path/to/fastq/files/"
#path to manifest files
sampleManifest: "OUTPUT_DIR/manifests/samples.tsv"
multiplexManifest: "OUTPUT_DIR/manifests/multiplex.tsv"
contrastManifest: "OUTPUT_DIR/manifests/contrasts.tsv"

########################################################################################
#user parameters
#########################################################################################
multiplexflag: "Y" #whether samples are multiplexed ["Y","N"]
umiSeparator: "rbc:" #required for nondemultiplexed samples to determine delimiter for deduplication [":", "_", "rbc:"]
mismatch: 1 #required for multiplexed samples, number of bp mismatches allowed in demultiplexing [1,2,3]
barcode_qc_flag: "PROCESS" #barcodes will undergo QC to ensure uniformity within samples; ["PROCESS", "IGNORE"]
min_reads_mapped: 0.5 #minimum percent of reads that should be mapped; IE .5 for 50% of all reads must be mapped [0.5]
reference: "" #reference organism ["hg38","mm10"]
filterlength: 20 #minimum read length to include in analysis [any int >20]
phredQuality: 20 #minimum quality score for 3’ end trimming
includerRNA: "Y" #whether to include refseq rRNA's in annotations ["Y", "N"]
splicejunction: "Y" #whether to include splice junctions in peak calls for DE_METHOD MANORM or DIFFBIND ["Y", "N"]
AnnoAnchor: "max_total" #whether annotations for spliced peaks will be based on either 5' most region or region with max reads ["max","5prime"]
mincount: 3 #minimum number of reads to count as a peak [1,2,3]
ntmerge: 10 #minimum distance of nucleotides to merge peaks [any integer >: 1, default 10]
peakid: "ALL" #report peaks for unique peaks only or unique and fractional mm ["unique","all"]
DEmethod: "none" #DE method ["none", "manorm", "diffbind"]
MANormWidth: 50 #Width of window to calculate read density. [any integer >1; default 50]
MNormDistance: 25 #Summit-to-summit distance cutoff for common peaks. [ any integer >1; default MANormWidth/2]
sampleoverlap: 1 #if DEmethod DIFFBIND, minimum number of samples a peak must be found in to be counted [>1]
pval: 0.005 #if DEmethod DIFFBIND or MANNORM, pval cutoff for significance
fc: 1 #if DEmethod DIFFBIND or MANNORM, fold change cut off for significance
single_qc_threshold: 95 #maximum threshold for unmampped reads in any single sample
project_qc_threshold: 50 #maximum threshold for unmapped reads across average of all project samples

#########################################################################################
# STAR parameters
#########################################################################################
alignEndsType: "Local" #type of read ends alignment ["Local", "EndToEnd", "Extend5pOfRead1", "Extend5pOfReads12"]
alignIntronMax: 50000 #maximum intron length
alignSJDBoverhangMin: 3 # minimum overhang value for annotated spliced junctions
alignSJoverhangMin: 5 # minimum overhang value for non-cannonical splied junctions
alignTranscriptsPerReadNmax: 10000 #max number of different alignments per read to consider [int>0]
alignWindowsPerReadNmax: 10000 #max number of windows per read [int>0]
limitOutSJcollapsed: 1000000 # max number of collapsed junctions [int>0]
outFilterMatchNmin: 15 # alignment will be output only if the number of matched bases is higher than or equal to this value.
outFilterMatchNminOverLread: 0.9 #alignment will be output only if the number of matched bases is >= to value; normalized to sum of mates’ lengths for paired-end reads
outFilterMismatchNmax: 999 #alignment will be output only if it has no more mismatches than this value.
outFilterMismatchNoverReadLmax: 0.04 #alignment will be output only if its ratio of mismatches to *read* length is less than or equal to this value.
outFilterMultimapNmax: 10000 #max number of multiple alignments allowed for a read: if exceeded, the read is considered unmapped
outFilterMultimapScoreRange: 0 #the score range below the maximum score for multimapping alignments
outFilterScoreMin: 0 #alignment will be output only if its score is higher than or equal to this value.
outFilterType: "Normal" #type of filtering ["Normal", "BySJout"]
outSAMattributes: "All" #a string of desired SAM attributes, in the order desired for the output SAM
outSAMunmapped: "None" #output of unmapped reads in the SAM format ["None", "Within"]
outSJfilterCountTotalMin: "3,1,1,1" #minimum total (multi-mapping+unique) read count per junction for: (1) non-canonical motifs, (2) GT/AG and CT/AC motif, (3) GC/AG and CT/GC motif, (4) AT/AC and GT/AT motif
outSJfilterOverhangMin: "30,12,12,12" #minimum overhang length for splice junctions on both sides for: (1) non-canonical motifs, (2) GT/AG and CT/AC motif, (3) GC/AG and CT/GC motif, (4) AT/AC and GT/AT motif
outSJfilterReads: "All" #which reads to consider for collapsed splice junctions output ["All", "Unique"]
seedMultimapNmax: 10000 #only pieces that map fewer than this value are utilized in the stitching procedure [int>0]
seedNoneLociPerWindow: 20 #max number of one seed loci per window [int>0]
seedPerReadNmax: 10000 #max number of seeds per read
seedPerWindowNmax: 500 #max number of seeds per window
sjdbScore: 2 #extra alignment score for alignmets that cross database junctions
winAnchorMultimapNmax: 500 #max number of loci anchors are allowed to map to

#########################################################################################
# modules, container parameters
#########################################################################################
containerDir: "/data/CCBR_Pipeliner/iCLIP/container"
fastq_val: "/data/CCBR_Pipeliner/iCLIP/bin/fastQValidator"

bedtools: "bedtools/2.29.2"
bowtie2: "bowtie/2-2.3.4"
fastq_screen: "fastq_screen/0.14.0"
fastqc: "fastqc/0.11.9"
manorm: "manorm/1.1.4"
multiqc: "multiqc/1.9"
perl: "perl/5.24.3"
python: "python/3.8"
R: "R/4.0"
samtools: "samtools/1.11"
star: "STAR/2.7.8a"
subread: "subread/2.0.1"
ultraplex: "ultraplex/1.2.5"
umitools: "umitools/1.1.1"

#########################################################################################
# dev
#########################################################################################
#testing parameter
testing_option: "N"
