#########################################################################################
# Global configuration file for the pipeline
#########################################################################################

#########################################################################################
#Folders and Paths
#########################################################################################
#path to iCLIP directory
sourceDir: "PIPELINE_HOME"
#path to output directory
outputDir: "OUTPUT_DIR"
#path to fastq files
fastqDir: "/path/to/fastq/files/"
#path to manifest files
sampleManifest: "OUTPUT_DIR/manifests/samples.tsv"
multiplexManifest: "OUTPUT_DIR/manifests/multiplex.tsv"
contrastManifest: "OUTPUT_DIR/manifests/contrasts.tsv"

########################################################################################
#user parameters
#########################################################################################
multiplexflag: "N" #whether samples are multiplexed ["Y","N"]
umiSeparator: "rbc:" #required for nondemultiplexed samples to determiner deliminator for deduplication [":", "_", "rbc:"]
mismatch: 1 #if multiplexed, number of bp mismatches allowed in demultiplexing [1,2,3]
reference: "mm10" #reference organism ["hg38","mm10"]
filterlength: 20 #minimum read length to include in analysis [any int >20]; this is also the novoalign l parameter
phredQuality: 20 #The minimum quality score for 3’ end trimming
includerRNA: "Y" #if spliceaware, include refseq rRNA's in annotations ["Y", "N"]
splicejunction: "Y" #if spliceaware Y, include splice junctions in peak calls for DE_METHOD MANORM or DIFFBIND ["Y", "N"]
AnnoAnchor: "max_total" #Annotations for spliced peaks will be based on either 5' most region or region with max reads ["max","5prime"]
mincount: 3 #minimum number of reads to count as a peak [1,2,3]
ntmerge: 10 #minimum distance of nucleotides to merge peaks [any integer >: 1, default 10]
peakid: "ALL" #report peaks for unique peaks only or unique and fractional mm ["unique","all"]
DEmethod: "none" #choose DE method ["none", "manorm", "diffbind"]
sampleoverlap: 1 #if DEmethod DIFFBIND, minimum number of samples a peak must be found in to be counted [>1]
pval: 0.005 #if DEmethod, pval cutoff for significance
fc: 1 #if DEmethod, fold change cut off for significance

#########################################################################################
# STAR parameters
#########################################################################################
alignEndsType: "Local"
alignIntronMax: 50000
alignSJDBoverhangMin: 3 # minimum overhang value for annotated spliced junctions
alignSJoverhangMin: 5 # minimum overhang value for non-cannonical splied junctions
alignTranscriptsPerReadNmax: 10000
alignWindowsPerReadNmax: 10000
outFilterMatchNmin: 15 # alignment will be output only if the number of matched bases is higher than or equal to this value.
outFilterMatchNminOverLread: 0.9
outFilterMismatchNmax: 999
outFilterMismatchNoverReadLmax: 0.04
outFilterMultimapNmax: 10000
outFilterMultimapScoreRange: 0
outFilterScoreMin: 0
outFilterType: "Normal"
outSAMattributes: "All"
outSAMunmapped: "None"
outSJfilterCountTotalMin: "3 1 1 1"
outSJfilterOverhangMin: "30 12 12 12"
outSJfilterReads: "All"
seedMultimapNmax: 10000
seedNoneLociPerWindow: 20
seedPerReadNmax: 10000
seedPerWindowNmax: 500
sjdbScore: 2
winAnchorMultimapNmax: 500

#########################################################################################
# modules, container parameters
#########################################################################################
containerDir: "/data/CCBR_Pipeliner/iCLIP/container"
fastq_val: "/data/CCBR_Pipeliner/iCLIP/bin/fastQValidator"

bedtools: "bedtools/2.29.2"
bowtie2: "bowtie/2-2.3.4"
fastq_screen: "fastq_screen/0.14.0"
fastqc: "fastqc/0.11.9"
manorm: "manorm/1.1.4"
multiqc: "multiqc/1.9"
perl: "perl/5.24.3"
python: "python/3.8"
R: "R/4.0"
samtools: "samtools/1.11"
star: "STAR/2.7.8a"
subread: "subread/2.0.1"
ultraplex: "ultraplex/1.2.5"
umitools: "umitools/1.1.1"

#########################################################################################
# dev
#########################################################################################
#testing parameter
testing_option: "N"
