# Global configuration file for the pipeline
#path to iCLIP directory
source_dir: "/path/to/iCLIP/"

#path to output directory
output_dir: "/path/to/output/dir/"

#path to manifest files
sample_manifest: "/path/to/manifest/samples.tsv"
multiplex_manifest: "/path/to/manifest/multiplex.tsv"
contrast_manifest: "/path/to/manifest/contrasts.tsv"

#path to fastq files
fastq_dir: "/path/to/fastq/files/"

#user parameters
multiplex_flag: "Y" #flag that samples are multiplexed ["Y","N"]
mismatch_allowance: 1 #number of bp mismatches allowed in demultiplexing [1,2,3]
split_value: 1000000 #number of sequences to split fastq file [min 3000, default 1000000]
novoalign_reference: "hg38" #reference organism ["mm10", "hg38"]
splice_aware: "Y" #whether to run splice_aware part of the pipeline ['y', 'n']
splice_bp_length: 75 #length of splice index to use [50, 75, 150]
minimum_count: 3 #minimum number of matches to count as a peak [1,2,3]
nt_merge: 50 #minimum distance of nucleotides to merge peaks [10,20,30,40,50,60]
peak_id: "ALL" #report peaks for unique peaks only or unique and fractional mm ["unique","all"]
DE_method: "MANORM" #choose DE method ["manorm","none"]
splice_junction: "Y" #include splice junctions in peak calls: "manorm" #choose DE method ["manorm","none"]
include_rRNA: "Y" #include refseq rRNA's in annotations ["Y", "N"]
condense_exon: "Y" #whether to collapse exons

#modules, container parameters
container_dir: "/data/CCBR_Pipeliner/iCLIP/container"
bedtools: "bedtools/2.29.2"
bowtie2: "bowtie/2-2.3.4"
fastq_screen: "fastq_screen/0.14.0"
fastqc: "fastqc/0.11.9"
java: "java/12.0.1"
manorm: "manorm/1.1.4"
multiqc: "multiqc/1.9"
novocraft: "novocraft/4.03.01"
perl: "perl/5.24.3"
python: "python/3.7"
Qt: "Qt/5.13.2"
singularity: "singularity"
samtools: "samtools/1.11"
umitools: "umitools/1.1.1"
subread: "subread/2.0.1"
R: "R/4.0"