# Global configuration file for the pipeline
#path to iCLIP directory
sourceDir: "/data/RBL_NCI/Pipelines/iCLIP/v1.0"

#path to output directory
outputDir: "/path/to/output/dir/"

#path to manifest files
sampleManifest: "/path/to/manifest/samples.tsv"
multiplexManifest: "/path/to/manifest/multiplex.tsv"
contrastManifest: "/path/to/manifest/contrasts.tsv"

#path to fastq files
fastqDir: "/path/to/fastq/files/"

#user parameters
filterlength: 20 #minimum read length to include in analysis [any int >20]
multiplexflag: "Y" #whether samples are multiplexed ["Y","N"]
mismatch: 1 #if multiplexed, number of bp mismatches allowed in demultiplexing [1,2,3]
reference: "hg38" #reference organism ["hg38","mm10"]
spliceaware: "Y" #whether to run include splice_aware feature for alignment ["Y","N"]
includerRNA: "Y" #if spliceaware, include refseq rRNA's in annotations ["Y", "N"]
spliceBPlength: 75 #if spliceaware Y, length of splice index to use [50, 75, 150]
splicejunction: "Y" #if spliceaware Y, include splice junctions in peak calls for DE_METHOD MANORM or DIFFBIND ["Y", "N"]
condenseexon: "Y" #if spliceaware Y, if there are multiple peaks in the same transcript, whether to combine into one feature ["Y", "N"]
mincount: 3 #minimum number of reads to count as a peak [1,2,3]
ntmerge: 50 #minimum distance of nucleotides to merge peaks [10,20,30,40,50,60]
peakid: "ALL" #report peaks for unique peaks only or unique and fractional mm ["unique","all"]
DEmethod: "MANORM" #choose DE method ["none", "manorm", "diffbind"]
sampleoverlap: 1 #if DEmethod DIFFBIND, minimum number of samples a peak must be found in to be counted [>1]
pval: 0.005 #if DEmethod, pval cutoff for significance
fc: 1 #if DEmethod, fold change cut off for significance

#modules, container parameters
containerDir: "/data/CCBR_Pipeliner/iCLIP/container"
bedtools: "bedtools/2.29.2"
bowtie2: "bowtie/2-2.3.4"
fastq_screen: "fastq_screen/0.14.0"
fastqc: "fastqc/0.11.9"
java: "java/12.0.1"
manorm: "manorm/1.1.4"
multiqc: "multiqc/1.9"
novocraft: "novocraft/4.03.01"
perl: "perl/5.24.3"
python: "python/3.7"
Qt: "Qt/5.13.2"
singularity: "singularity"
samtools: "samtools/1.11"
umitools: "umitools/1.1.1"
subread: "subread/2.0.1"
R: "R/4.0"