# Global configuration file for the pipeline
#path to snakemake file
source_dir: ""

#path to output directory
output_dir: "hg38_full/"

#path to manifest files
sample_manifest: ".tests/sample_hg38_full.tsv"
multiplex_manifest: ".tests/multiplex_hg38_full.tsv"

#path to fastq files
fastq_dir: ".tests/"

#path to containers
container_dir: "container"

#user parameters
split_value: 2000000 #number of sequences in split files [min 3000, default 1000000]
novoalign_reference: "hg38" #options: mm10 hg38
splice_aware: 'y' #options: Y or N
splice_bp_length: 75 # options: if splice_aware = Y, 50,75,150
minimum_count: 2 #minimum number of matches to count as a true peak
