$schema: "http://json-schema.org/draft-04/schema#"

description: snakemake configuration file

type: object

# possible entries of the config file and which type they should be
properties:
  sourceDir:
    type: string
    description: /path/to/iCLIP/dir
  outputDir:
    type: string
    description: /path/to/output/dir
  sampleManifest:
    type: string
    description: /path/to/sample/manifest
  multiplexManifest:
    type: string
    description: /path/to/multiplex/manifest
  contrastManifest:
    type: string
    description: /path/to/contrast/manifest
  containerDir:
    type: string
    description: /path/to/container/sif/files
  fastq_val:
    type: string
    description: /path/to/fastQValidator
  fastqDir:
    type: string
    description: /path/to/fastq/files
  filterlength: 
    types: number
    description: minimum read length to include in analysis, any int greater than 20
  multiplexflag:
    types: string
    enum: ["Y","N","y","n"]
    description: determine whether or not samples are multiplexed
  mismatch:
    types: number
    enum: [1,2,3]
    description: number of bp mismatches allowed in demultiplexing
  reference:
    type: string
    enum: ["hg38","mm10"]
    description: reference organism
  spliceaware:
    type: string
    enum: ["Y","N","y","n"]
    description: whether to run include splice_aware feature for alignment
  includerRNA:
    type: string
    enum: ["Y","N","y","n"]
    description: if spliceaware, include refseq rRNA's in annotations
  spliceBPlength:
    type: number
    enum: [50,75]
    description: bp length of created index
  splicejunction: 
    type: string
    enum: ["Y","N","y","n"]
    description: if spliceaware Y, include splice junctions in peak calls for DE_METHOD MANORM or DIFFBIND
  AnnoAnchor:
    type: string
    enum: ["max_MM","max_total","5prime"]
    description: Annotations for spliced peaks will be based on either 5` most region or region with max reads based on Count_FracMM (max_mm) or total reads (max_total)
  mincount:
    type: number
    description: minimum number of values to count as a 'peak'
  ntmerge:
    type: number
    description: minimum distance of nucleotides to merge peaks
  peakid:
    type: string
    enum: ["all","ALL","unique","UNIQUE"]
    description: report peaks for unique peaks only or unique and fractional mm
  DEmethod:
    type: string
    enum: ["MANORM","manorm","none","NONE", "DIFFBIND","diffbind"]
    description: DE method option  
  sampleoverlap:
    type: number
    description: if DEmethod DIFFBIND, minimum number of samples a peak must be found in to be counted 
  pval: 
    type: number
    description: if DEmethod, pval cutoff for significance
  fc:
    type: number
    description: if DEmethod, fold change cut off for significance

# entries that have to be in the config file for successful validation
required:
  - sourceDir
  - outputDir
  - sampleManifest
  - multiplexManifest
  - contrastManifest
  - fastqDir
  - containerDir
  - fastq_val
  - filterlength
  - multiplexflag
  - mismatch
  - reference
  - spliceaware
  - includerRNA
  - spliceBPlength
  - splicejunction
  - AnnoAnchor
  - mincount
  - ntmerge
  - peakid
  - DEmethod
  - sampleoverlap
  - pval
  - fc