name: Tests

on:
  push:
    branches:
      - master
      - main
      - activeDev
  pull_request:
    branches_ignore: []

jobs:
  Dryrun_Lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker://snakemake/snakemake:v5.24.2
    - name: Dry-run pipeline
      run: |
        docker run -v $PWD:/tmp/repo snakemake/snakemake:v5.24.2 bash /tmp/repo/run_snakemake.sh test        
    - name: Lint workflow
      continue-on-error: true
      run: |
        docker run -v $PWD:/tmp/repo snakemake/snakemake:v5.24.2 snakemake --lint -s /tmp/repo/workflow/Snakefile --configfile=/tmp/repo/config/snakemake_config.yaml || \
        echo 'There may have been a few warnings or errors. Please read through the log to determine if its harmless.'
